### ISSUE TITLE
Upgrade to node16

### ISSUE THREAD

**Issue by brandonbirdj** [codespell-project/codespell-problem-matcher#6]
When using this action the following error is emitted requesting node be upgraded.

>The following actions uses node12 which is deprecated and will be forced to run on node16: codespell-project/codespell-problem-matcher@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by peternewman** [comment]
The PR had been merged for ages to do this, but we hadn't cut a new release. I've now released https://github.com/codespell-project/codespell-problem-matcher/releases/tag/v1.2.0 with it in.

FWIW I assume you're aware of https://github.com/codespell-project/actions-codespell which does all the checking too, not just the matching for you?
